# Generated by Django 4.1.2 on 2022-10-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_alter_donation_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories'},
        ),
    ]
