# Generated by Django 4.1.2 on 2022-10-26 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
