# Generated by Django 4.1.2 on 2022-11-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('FOUNDATION', 'Fundacja'), ('NON-GOVERNMENTAL ORGANISATION', 'Organizacja pozarządowa'), ('LOCAL COLLECTION', 'Zbiórka lokalna')], default='FOUNDATION', max_length=64),
        ),
    ]
