# Generated by Django 4.1.2 on 2022-11-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_alter_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.CharField(choices=[('TAKEN', 'zabrany'), ('NOT TAKEN', 'do odbioru')], default='NOT TAKEN', max_length=64),
        ),
    ]
