# Generated by Django 4.1.2 on 2022-11-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data_send',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
