# Generated by Django 4.1.2 on 2022-11-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0013_alter_contactform_data_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='data_send',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
