# Generated by Django 4.1.2 on 2022-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_alter_contactform_data_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
